# Generated by Django 5.2.13 on 2026-07-21 08:24

import common.db.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0020_favoritefolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSyncAccount',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('provider', models.CharField(choices=[('aws', 'Amazon Web Services'), ('azure', 'Microsoft Azure')], max_length=16, verbose_name='Provider')),
                ('credentials', common.db.fields.EncryptJsonDictTextField(default=dict, verbose_name='Credentials')),
                ('regions', models.JSONField(blank=True, default=list, verbose_name='Regions')),
                ('hostname_strategy', models.CharField(choices=[('instance_name', 'Instance name'), ('instance_id', 'Instance ID')], default='instance_name', max_length=32, verbose_name='Hostname strategy')),
                ('use_public_ip', models.BooleanField(default=False, verbose_name='Use public IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last sync')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_sync_accounts', to='assets.node', verbose_name='Target node')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.platform', verbose_name='Default platform')),
            ],
            options={
                'verbose_name': 'Cloud sync account',
                'unique_together': {('org_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CloudSyncExecution',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='cloud_sync.cloudsyncaccount')),
            ],
            options={
                'verbose_name': 'Cloud sync execution',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='CloudSyncedAsset',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('instance_id', models.CharField(max_length=256, verbose_name='Instance ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_assets', to='cloud_sync.cloudsyncaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_synced', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Cloud synced asset',
                'unique_together': {('account', 'instance_id')},
            },
        ),
    ]
