ARG VERSION=dev
FROM python:3.14-slim-trixie AS gmssl-builder
WORKDIR /app
ARG GMSSL_VERSION=3.1.1
RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
        cmake \
        make \
        gcc \
        g++ \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN set -ex \
    && git clone --branch v${GMSSL_VERSION} https://github.com/guanzhi/GmSSL.git \
    && cd GmSSL \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && make -j"$(nproc)" \
    && make install

FROM registry.fit2cloud.com/jumpserver/xpack:${VERSION} AS build-xpack
FROM jumpserver/core:${VERSION}-ce

COPY --from=build-xpack /opt/xpack /opt/jumpserver/apps/xpack

ARG TOOLS="                           \
        g++                           \
        iputils-ping                  \
        netcat-openbsd                \
        telnet"

RUN set -ex \
    && apt-get update \
    && apt-get -y install --no-install-recommends ${TOOLS} \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/jumpserver

ARG PIP_MIRROR=https://pypi.org/simple

ARG GMSSL_VERSION=3.1.1

RUN set -ex \
    && uv pip install -i${PIP_MIRROR} --group xpack \
    && rm -rf /root/.cache/

COPY --from=gmssl-builder /usr/local/lib/libgmssl.so* /usr/local/lib/
COPY --from=gmssl-builder /usr/local/include/gmssl /usr/local/include/gmssl
COPY --from=gmssl-builder /usr/local/bin/gmssl /usr/local/bin/gmssl
